package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */

@Data
@Entity
@Table(name = "Notification")
public class Notification implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "notification_id", unique = true, nullable = false)
	private Integer notificationId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id")
	private Account account;

	@Column(name = "message", nullable = false)
	private String message;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	private Date createdAt;

	@Column(name = "is_read")

	private Boolean isRead;

	public Notification() {
	}

	public Notification(String message, Date createdAt) {
		this.message = message;
		this.createdAt = createdAt;
	}

	public Notification(Account account, String message, Date createdAt, Boolean isRead) {
		this.account = account;
		this.message = message;
		this.createdAt = createdAt;
		this.isRead = isRead;
	}

}
