package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductColor generated by hbm2java
 */

@Data
@Entity
@Table(name = "ProductColor")
public class ProductColor implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_color_id", unique = true, nullable = false)
	private Integer productColorId;

	@Column(name = "color_name")
	private String colorName;

	@Column(name = "color_type")
	private String colorType;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productColor")
	private Set<ProductVariant> productVariants = new HashSet<ProductVariant>(0);

	public ProductColor() {
	}

	public ProductColor(String colorName,String colorType) {
		this.colorName = colorName;
		this.colorType = colorType;
	}

	public ProductColor(String colorName,String colorType, Set<ProductVariant> productVariants) {
		this.colorName = colorName;
		this.colorType = colorType;
		this.productVariants = productVariants;
	}

}
