package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductStyle generated by hbm2java
 */

@Data
@Entity
@Table(name = "ProductStyle")
public class ProductStyle implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_style_id", unique = true, nullable = false)
	private Integer productStyleId;

	@Column(name = "style_name")
	private String styleName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productStyle")
	private Set<Product> products = new HashSet<Product>(0);

	public ProductStyle() {
	}

	public ProductStyle(String styleName, Set<Product> products) {
		this.styleName = styleName;
		this.products = products;
	}

}
