package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductBrand generated by hbm2java
 */

@Data
@Entity
@Table(name="ProductBrand")
public class ProductBrand implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_brand_id", unique = true, nullable = false)
	private Integer productBrandId;

	@Column(name = "brand_name")
	private String brandName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productBrand")
	private Set<Product> products = new HashSet<Product>(0);

	public ProductBrand() {
	}

	public ProductBrand(String brandName, Set<Product> products) {
		this.brandName = brandName;
		this.products = products;
	}

}
